---
# Updates Homebrew to use the the latest version.
- name: Updates Homebrew
  command: brew update

# Upgrades existing Homebrew packages, if any.
- name: Upgrades existing Homebrew packages (if any)
  command: brew upgrade

# Installs latest Homebrew command line tools.
- name: Install command line applications using Homebrew
  homebrew:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - curl
      - gcc
      - git
      - go
      - node
      - python3
      - wget
      - php
      - mysql
      - postgresql@12

# Installs latest GUI applications for MacOS.
- name: Install GUI applications using Homebrew Casks for MacOS
  homebrew_cask:
    name: "{{ applications }}"
    state: latest
  when: ansible_facts["os_family"] == "Darwin"
  vars:
    applications:
      - docker
      - google-backup-and-sync
      - slack
      - visual-studio-code
      - zoom

# Cleans up old and cached files.
- name: Homebrew cleanup
  command: brew cleanup

# Autoremoves old, unused dependencies.
- name: Homebrew autoremove
  command: brew autoremove
